include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - lib/di/di.config.dart
    - "**.freezed.dart"
    - "**.g.dart"
    - "**_generated**.dart"
  errors:
    invalid_annotation_target: ignore
