targets:
  $default:
    sources:
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/data/*.dart
          - lib/data/**/*.dart
          - lib/http/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/http/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/*.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/di/*.dart
          - lib/di/**/*.dart
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/http/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/*.dart
      freezed:
        generate_for:
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/data/*.dart
          - lib/data/**/*.dart
          - lib/*_cubit.dart
          - lib/**/*_cubit.dart
          - lib/*_bloc.dart
          - lib/**/*_bloc.dart
          - lib/*_state.dart
          - lib/**/*_state.dart
          - lib/feature/**/*.dart
