targets:
  $default:
    sources:
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      reflectable:
        generate_for:
        options:
          formatted: true

      json_serializable:
        options:
          explicit_to_json: true
