name: app

packages:
  - packages/**
  - .

scripts:
  decrypt-secrets:
    description: Decrypt secrets
    run: bash scripts/decrypt-secrets.sh

  codegen:
    description: Generate code for all packages
    exec: "flutter packages pub run build_runner build --delete-conflicting-outputs"
    # concurrency set to ONE because we SHOULD generate all code for packages prior we
    # started generation for the app
    concurrency: 1
    failFast: true
    packageFilters:
      dependsOn: "build_runner"

  # TODO(nesquikm): we have to isolane runing dart_code_metrics for the main app because we
  # can't add dart_code_metrics to the app due to dependency incompatibility
  analyze:
    description: Analyze all packages and run dart_code_metrics for the main app
    run: melos run analyze_subpackages --no-select && cd packages/ui_components_lib && flutter pub run dart_code_metrics:metrics analyze ../../lib
    failFast: true

  analyze_subpackages:
    description: Analyze a specific package in this project.
    exec: flutter analyze . && flutter pub run dart_code_metrics:metrics analyze lib
    failFast: true
    packageFilters:
      dependsOn: "dart_code_metrics"

  check-format:
    description: Check the format of a specific package in this project.
    exec: dart format --set-exit-if-changed .
    failFast: true

  test:
    description: Run all Dart & Flutter tests in this project.
    run: melos run test:dart --no-select && melos run test:flutter --no-select

  test:dart:
    description: Run Dart tests for a specific package in this project.
    exec: "dart test test"
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    description: Run Flutter tests for a specific package in this project.
    exec: "flutter test test"
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: test

  test:integration:
    description: Run Flutter teintegration teststs for a specific package in this project.
    # TODO(nesquikm): Maybe we should separate integration_test for the app and packages
    # because packages may not use flavors at all
    exec: "flutter test --flavor production integration_test"
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: integration_test

  check-all:
    description: Prepare to commit by checking all things
    run: melos check-format && melos analyze && melos test && melos test:integration
    failFast: true

  build:storybook:
    description: Build the storybook
    run: bash scripts/build-storybook.sh

  build:ios_match_assure:
    description: Making sure the iOS certificates and profiles are installed
    run: bash scripts/ios-match-assure.sh

  build:ios_match_new_devices:
    description: Registering new devices already added through devportal
    run: bash scripts/ios-match-new-devices.sh

  build:deploy_fad:
    description: Build and deploy to FAD
    run: bash scripts/build-deploy-fad.sh

  build:deploy_store:
    description: Build and deploy to Testflight and Google Play internal
    run: bash scripts/build-deploy-store.sh

  build:deploy_fad_store:
    description: Build and deploy to FAD, Testflight and Google Play internal
    run: bash scripts/build-deploy-fad-store.sh

command:
  clean:
    hooks:
      post: bash scripts/clean.sh
