name: app

packages:
  - packages/**
  - .

scripts:
  codegen:
    exec: "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: Generate code for all packages
    # concurrency set to ONE because we SHOULD generate all code for packages prior we
    # started generation for the app
    concurrency: 1
    failFast: true
    packageFilters:
      dependsOn: "build_runner"

  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    failFast: true
    description: Check the format of a specific package in this project.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    exec: "dart test test"
    description: Run Dart tests for a specific package in this project.
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    exec: "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: test

  test:integration:
    exec: "flutter test integration_test"
    description: Run Flutter teintegration teststs for a specific package in this project.
    concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: integration_test

  check-all:
    run: melos analyze && melos test && melos test:integration
    description: Prepare to commit by checking all things
    failFast: true

  build:storybook:
    run: bash scripts/build-storybook.sh
    description: Build the storybook

command:
  clean:
    hooks:
      post: bash scripts/clean.sh
