name: app

packages:
  - packages/**
  - .

scripts:
  codegen:
    run: melos exec -c 1 --fail-fast -- "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: Generate code for all packages
