name: app

packages:
  - .
  - packages/**

scripts:
# TODO: Melos skips pub get for root packages, so we call it directly
  bootstrap:
    run: flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Bootstrap packages

  codegen:
    run: flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generate code for all packages

  clean:
    run: flutter clean
    description: Clean all
