name: app

packages:
  - packages/**


scripts:
  codegen:
    run: flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generate code for all packages

  clean:
    run: flutter clean
    description: Clean all
