name: encrypted_storage
description: Encrypted storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  injectable: ^2.1.1
  logging: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
