import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:ui_components_lib/ui_components_lib.dart';
import 'package:ui_components_lib/v2/widgets/buttons/button.dart';

class ButtonsStoryV2 extends StatelessWidget {
  const ButtonsStoryV2({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Buttons v2')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(DimensSize.d16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AccentButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            AccentButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.medium,
            ),
            const SizedBox(height: DimensSize.d16),
            AccentButton(
              buttonShape: ButtonShape.pill,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              buttonSize: ButtonSize.small,
            ),
            const SizedBox(height: DimensSize.d16),
            AccentButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              isLoading: true,
            ),
            const SizedBox(height: DimensSize.d16),
            const AccentButton(
              buttonShape: ButtonShape.rectangle,
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            const Divider(),
            const SizedBox(height: DimensSize.d16),
            PrimaryButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            PrimaryButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              buttonSize: ButtonSize.medium,
            ),
            const SizedBox(height: DimensSize.d16),
            PrimaryButton(
              buttonShape: ButtonShape.pill,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.small,
            ),
            const SizedBox(height: DimensSize.d16),
            PrimaryButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              isLoading: true,
            ),
            const SizedBox(height: DimensSize.d16),
            const PrimaryButton(
              buttonShape: ButtonShape.rectangle,
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            const Divider(),
            const SizedBox(height: DimensSize.d16),
            FloatButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            FloatButton(
              buttonShape: ButtonShape.pill,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.medium,
            ),
            const SizedBox(height: DimensSize.d16),
            FloatButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              buttonSize: ButtonSize.small,
            ),
            const SizedBox(height: DimensSize.d16),
            FloatButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              postfixIcon: LucideIcons.apple,
              isLoading: true,
            ),
            const SizedBox(height: DimensSize.d16),
            const FloatButton(
              buttonShape: ButtonShape.pill,
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            const Divider(),
            const SizedBox(height: DimensSize.d16),
            GhostButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            GhostButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.medium,
            ),
            const SizedBox(height: DimensSize.d16),
            GhostButton(
              buttonShape: ButtonShape.pill,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.small,
            ),
            const SizedBox(height: DimensSize.d16),
            GhostButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              isLoading: true,
            ),
            const SizedBox(height: DimensSize.d16),
            const GhostButton(
              buttonShape: ButtonShape.rectangle,
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const SizedBox(height: DimensSize.d16),
            const Divider(),
            const SizedBox(height: DimensSize.d16),
            DestructiveButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
            ),
            const SizedBox(height: DimensSize.d16),
            DestructiveButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.medium,
            ),
            const SizedBox(height: DimensSize.d16),
            DestructiveButton(
              buttonShape: ButtonShape.pill,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              buttonSize: ButtonSize.small,
            ),
            const SizedBox(height: DimensSize.d16),
            DestructiveButton(
              buttonShape: ButtonShape.rectangle,
              onPressed: () {},
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
              isLoading: true,
            ),
            const SizedBox(height: DimensSize.d16),
            const DestructiveButton(
              buttonShape: ButtonShape.rectangle,
              title: 'Button label',
              icon: LucideIcons.heart,
              postfixIcon: LucideIcons.apple,
            ),
            const Divider(),
            Row(
              children: [
                AccentButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.apple,
                ),
                const SizedBox(width: 4),
                AccentButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.pen,
                ),
                const SizedBox(width: 4),
                PrimaryButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.cat,
                ),
                const SizedBox(width: 4),
                PrimaryButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.cake,
                ),
                const SizedBox(width: 4),
                FloatButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.cake,
                ),
              ],
            ),
            const SizedBox(height: 4),
            Row(
              children: [
                AccentButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.plus,
                  buttonSize: ButtonSize.medium,
                ),
                const SizedBox(width: 4),
                AccentButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.pen,
                  buttonSize: ButtonSize.medium,
                ),
                const SizedBox(width: 4),
                PrimaryButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.minus,
                  buttonSize: ButtonSize.medium,
                ),
                const SizedBox(width: 4),
                DestructiveButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.cake,
                  buttonSize: ButtonSize.medium,
                ),
                const SizedBox(width: 4),
                FloatButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.delete,
                  buttonSize: ButtonSize.medium,
                ),
              ],
            ),
            const SizedBox(height: 4),
            Row(
              children: [
                AccentButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.laptop,
                  buttonSize: ButtonSize.small,
                ),
                const SizedBox(width: 4),
                GhostButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.lamp,
                  buttonSize: ButtonSize.small,
                ),
                const SizedBox(width: 4),
                PrimaryButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.antenna,
                  buttonSize: ButtonSize.small,
                ),
                const SizedBox(width: 4),
                DestructiveButton(
                  buttonShape: ButtonShape.square,
                  onPressed: () {},
                  icon: LucideIcons.dog,
                  buttonSize: ButtonSize.small,
                ),
                const SizedBox(width: 4),
                FloatButton(
                  buttonShape: ButtonShape.circle,
                  onPressed: () {},
                  icon: LucideIcons.car,
                  buttonSize: ButtonSize.small,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
