name: datetime_avoid_lint
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^7.1.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.1
  # path: ^1.8.0

dev_dependencies:
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: main
  lints: ^5.1.1
  test: ^1.21.0
