name: nekoton_repository
description: Nekoton repository package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_nekoton_bridge:
    git:
      url: https://github.com/nesquikm/nekoton_bridge.git
      ref: nekoton_bridge-v1.5.0-dev.0
      path: packages/flutter_nekoton_bridge
  injectable: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
