name: nekoton_repository
description: Nekoton repository package
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  encrypted_storage:
    path: ../encrypted_storage
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_nekoton_bridge:
    git:
      url: https://github.com/broxus/nekoton_bridge.git
      ref: flutter_nekoton_bridge-v1.8.0-dev.9
      path: packages/flutter_nekoton_bridge
  get_it: ^7.6.0
  injectable: ^2.1.0
  logging: ^1.1.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
