name: Build and test main app

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build_and_test:
    runs-on: macos-latest
    env:
      SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2

      - name: Decrypt secrets
        run: melos decrypt-secrets

      # Dart/Flutter
      - name: Check Dart format
        run: melos run check-format --no-select
      - name: Generate dart code
        run: melos codegen --no-select
      - name: Dart code analysis
        run: melos run analyze --no-select
      - name: Run all Dart & Flutter tests
        run: melos run test --no-select


  ios_integration_test:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2

      - name: Generate dart code
        run: melos codegen --no-select

      - name: Start iOS Simulator
        run: |
          DEVICE_ID=$(xcrun xctrace list devices | grep iPhone | head -1 | awk '{print $NF}' | tr -d '()')
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
          xcrun simctl boot $DEVICE_ID

      - name: Run Flutter integration tests
        working-directory: .
        run: flutter test --flavor production -d ${{ env.DEVICE_ID }} integration_test

  android_integration_test:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11.x"


      - name: Generate dart code
        run: melos codegen --no-select

      - name: Run Flutter integration tests
        uses: Wandalen/wretry.action@master # sometimes android tests are flaky
        with:
          attempt_limit: 5
          action: reactivecircus/android-emulator-runner@v2
          with: |
            api-level: 33
            target: google_apis
            arch: x86_64
            ram-size: 1024M
            disk-size: 2048M
            script: flutter test --flavor production -d `flutter devices | grep android | tr ' ' '\n' | grep emulator-` integration_test
