name: Build and test main app

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build_and_test:
    uses: broxus/flutter_templates/.github/workflows/run-melos.yaml@main

  ios_integration_test:
    uses: broxus/flutter_templates/.github/workflows/ios-integration-test.yaml@main

  android_integration_test:
    uses: broxus/flutter_templates/.github/workflows/android-integration-test.yaml@main
