name: app

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: macos-latest

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2

      # Dart/Flutter
      - name: Check Dart format
        run: melos run check-format --no-select
      - name: Generate dart code
        run: melos codegen --no-select
      - name: Dart code analysis
        run: melos run analyze --no-select
      - name: Run all Dart & Flutter tests
        run: melos run test --no-select
