name: Version main app

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: "--prerelease"
        type: choice
        options:
          - "--prerelease"
          - "--graduate"

jobs:
  version_bump:
    uses: broxus/flutter_templates/.github/workflows/version.yaml@flutter-3.24.0
    with:
      version_parameters: ${{ inputs.version_parameters }}
      user_name: 'nesquikm'
      user_email: 'drapolyuk@gmail.com'
      push_tags: true
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN }}
